---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending

# Note: Autolabeling is handled by .github/workflows/labeler.yaml
# using actions/labeler (file-based) and github/issue-labeler (body-based)
# These support sync-labels to remove labels when patterns no longer match.

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
categories:
  - title: "⚠️ Breaking Changes"
    labels:
      - "breaking-change"
  - title: "🆕 Enhancements"
    labels:
      - "enhancement"
  - title: "✅ Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "⚓ Code Quality"
    labels:
      - "code-quality"
  - title: "📝 Documentation"
    collapse-after: 1
    labels:
      - "documentation"
  - title: "📦 Dependencies"
    collapse-after: 1
    labels:
      - "dependencies"
      - "pre-commit"
  - title: "🧹 Housekeeping"
    collapse-after: 1
    labels:
      - "github-config"
# yamllint disable rule:line-length
template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/raman325/ha-integration-tester/$RESOLVED_VERSION/total.svg)](https://github.com/raman325/ha-integration-tester/releases/$RESOLVED_VERSION)

  $CHANGES

  ## Links
  - [Submit bugs/feature requests](https://github.com/raman325/ha-integration-tester/issues)
